# .github/workflows/deploy_prebuilt_docs.yml

name: Deploy Pre-built Sphinx Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Solo se necesita un trabajo (job) que se encargue de subir y desplegar
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      # (Paso Opcional: crea .nojekyll si no está en tu repo local)
      - name: Crear .nojekyll si no existe
        run: touch docs/_build/html/.nojekyll

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Subir el Artefacto (artifact) de la Documentación
        uses: actions/upload-pages-artifact@v3
        with:
          # Apunta a la carpeta que subiste a GitHub
          path: 'docs/_build/html' 

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
